#ifndef _FTD_FIELD_H
#define _FTD_FIELD_H
#endif

#define FID_BulletinField           0x0001
#define FID_ClientField             0x0002
#define FID_DepositField            0x0003
#define FID_DisseminationstartField 0x0004
#define FID_ErrorField              0x0005
#define FID_ErrorTargetOrderField   0x002D
#define FID_ErrorTargetSequenceField 0x002E
#define FID_ForceExitField           0x0006
#define FID_InstrumentField          0x0007
#define FID_InstrumentStatusField    0x0008
#define FID_MarketField              0x0009
#define FID_MarketMatchDataChgField  0x0012
#define FID_MarketMatchDataField     0x0013
#define FID_MarketStatusField        0x0009
#define FID_OrderActionField         0x000B
#define FID_OrderInsertField         0x000C
#define FID_OrderStatusField         0x000E
#define FID_ParticipantField         0x000F
#define FID_PositionField            0x0010
#define FID_PPositionField           0x0011
#define FID_ReqQryClientField        0x0014
#define FID_ReqQryDepositField       0x0015
#define FID_ReqQryInstrumentField    0x0016
#define FID_ReqQryInstrumentStatusField 0x0017
#define FID_ReqQryMarketField           0x0018
#define FID_ReqQryMarketMatchField      0x001F
#define FID_ReqQryMarketOrderDataField  0x001B
#define FID_ReqQryMarketStatusField     0x0019
#define FID_ReqQryOrderField            0x001A
#define FID_ReqQryParticipantField      0x001C
#define FID_ReqQryPositionField         0x001D
#define FID_ReqQryPPositionField        0x001E
#define FID_ReqQryTradeField            0x0020
#define FID_ReqQryUserField             0x0021
#define FID_ReqQryUserLoginField        0x0022
#define FID_ReqUserLoginField           0x0023
#define FID_ReqUserLogoutField          0x0024
#define FID_ReqUserPasswordUpdateField  0x0025
#define FID_RspUserLoginField           0x0027
#define FID_RspUserLogoutField          0x0028
#define FID_RspUserPasswordUpdateField  0x0029
#define FID_TradeInsertSingleField      0x002A
#define FID_UserField                   0x002B
#define FID_UserLoginField              0x002C
#define FID_InputQuoteField             0x002D
#define FID_QuoteField                  0x002E
#define FID_QryQuoteField               0x002F
#define FID_EnquireQuoteField           0x0030
#define FID_EnquireQuoteNotifyField     0x0031
#define FID_InputExecOrderField         0x0032
#define FID_ExecOrderActionField        0x0033